In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red.csv')

In [27]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

##Separate Features and Target
* Here we are considering 'quality' as target
* and rest of the columns as features

In [28]:
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

##Splitting Data into Train and Test sets

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

##Standardization

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc = StandardScaler()

In [33]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

##Train on different algorithms


In [34]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [35]:
l_cla = LogisticRegression()
k_cla = KNeighborsClassifier()
d_cla = DecisionTreeClassifier()
r_cla = RandomForestClassifier()
s_cla = SVC(kernel='linear')
ks_cla = SVC(kernel='rbf')

In [36]:
l_cla.fit(x_train, y_train)
k_cla.fit(x_train, y_train)
d_cla.fit(x_train, y_train)
r_cla.fit(x_train, y_train)
s_cla.fit(x_train, y_train)
ks_cla.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [37]:
l_pred = l_cla.predict(x_test)
k_pred = k_cla.predict(x_test)
d_pred = d_cla.predict(x_test)
r_pred = r_cla.predict(x_test)
s_pred = s_cla.predict(x_test)
ks_pred = ks_cla.predict(x_test)

In [38]:
from sklearn.metrics import confusion_matrix

In [39]:
l_c = confusion_matrix(y_test, l_pred)
k_c = confusion_matrix(y_test, k_pred)
d_c = confusion_matrix(y_test, d_pred)
r_c = confusion_matrix(y_test, r_pred)
s_c = confusion_matrix(y_test, s_pred)
ks_c = confusion_matrix(y_test, ks_pred)

In [40]:
l_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  5,  1,  0,  0],
       [ 1,  0, 86, 45,  0,  0],
       [ 0,  1, 43, 72, 12,  0],
       [ 0,  0,  3, 29, 15,  0],
       [ 0,  0,  0,  3,  2,  0]])

In [41]:
k_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  3,  3,  0,  0],
       [ 1,  3, 82, 40,  6,  0],
       [ 0,  1, 34, 77, 16,  0],
       [ 0,  0,  7, 19, 21,  0],
       [ 0,  0,  0,  1,  4,  0]])

In [42]:
d_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 1,  1,  3,  1,  0,  0],
       [ 1,  2, 92, 32,  4,  1],
       [ 0,  5, 31, 77, 13,  2],
       [ 0,  0,  3, 18, 24,  2],
       [ 0,  0,  1,  0,  3,  1]])

In [43]:
r_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  4,  2,  0,  0],
       [ 0,  1, 93, 36,  2,  0],
       [ 0,  0, 24, 95,  9,  0],
       [ 0,  0,  1, 19, 27,  0],
       [ 0,  0,  0,  2,  2,  1]])

In [44]:
s_c

array([[ 0,  0,  2,  0,  0,  0],
       [ 0,  0,  5,  1,  0,  0],
       [ 0,  0, 92, 40,  0,  0],
       [ 0,  0, 46, 82,  0,  0],
       [ 0,  0,  3, 44,  0,  0],
       [ 0,  0,  0,  5,  0,  0]])

In [45]:
ks_c

array([[ 0,  0,  1,  1,  0,  0],
       [ 0,  0,  4,  2,  0,  0],
       [ 0,  0, 93, 37,  2,  0],
       [ 0,  0, 37, 83,  8,  0],
       [ 0,  0,  2, 29, 16,  0],
       [ 0,  0,  0,  3,  2,  0]])

##Result

In [46]:
from sklearn.metrics import accuracy_score

In [47]:
l_a = accuracy_score(y_test, l_pred)
k_a = accuracy_score(y_test, k_pred)
d_a = accuracy_score(y_test, d_pred)
r_a = accuracy_score(y_test, r_pred)
s_a = accuracy_score(y_test, s_pred)
ks_a = accuracy_score(y_test, ks_pred)

In [48]:
print('Logistic Regression: ' + str(l_a) + '\nKNN: ' + str(k_a) + '\nDecision Tree: ' + str(d_a) + '\nRandom Forest: ' + str(r_a) + '\nLinear SVC: ' + str(s_a) + '\nKernel SVC: ' + str(ks_a))

Logistic Regression: 0.540625
KNN: 0.5625
Decision Tree: 0.609375
Random Forest: 0.675
Linear SVC: 0.54375
Kernel SVC: 0.6
